# Generated by Django 5.2.8 on 2025-11-22 17:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_submission_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_html',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
