# Generated by Django 5.2.8 on 2025-12-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='time_taken_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
