# Generated by Django 5.2.8 on 2025-12-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating_difficulty',
            field=models.IntegerField(default=0, help_text='Difficulty (1-5)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_relevance',
            field=models.IntegerField(default=0, help_text='Relevance (1-5)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating_ui',
            field=models.IntegerField(default=0, help_text='UI/UX (1-5)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(help_text='Overall Experience (1-5)'),
        ),
    ]
