# Generated by Django 5.2.8 on 2025-12-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_feedback_rating_difficulty_feedback_rating_relevance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If unchecked, users cannot start this quiz'),
        ),
    ]
